const id = Math.random().toString()

export const configForm = [
  {
    id,
    name: 'cep',
    type: 'number',
    placeholder: 'cep',
    maxLength: 9,
    minLength: 1,
    register: {},
  },
  {
    id,
    name: 'rua',
    type: 'text',
    placeholder: 'rua',
    maxLength: 40,
    minLength: 1,
    register: {},
  },
  {
    id,
    name: 'numero',
    type: 'number',
    placeholder: 'numero',
    maxLength: 6,
    minLength: 1,
    register: {},
  },
  {
    id,
    name: 'complemento',
    type: 'text',
    placeholder: 'complemento',
    maxLength: 20,
    minLength: 1,
    register: {},
  },
  {
    id,
    name: 'bairro',
    type: 'text',
    placeholder: 'bairro',
    maxLength: 25,
    minLength: 1,
    register: {},
  },
  {
    id,
    name: 'uf',
    type: 'text',
    placeholder: 'uf',
    maxLength: 3,
    minLength: 1,
    register: {},
  },
  {
    id,
    name: 'cidade',
    type: 'text',
    placeholder: 'cidade',
    maxLength: 15,
    minLength: 1,
    register: {},
  },
]
